# Generated by Django 5.2.6 on 2025-09-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subscription service', max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost of the subscription', max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Billing frequency', max_length=10)),
                ('start_date', models.DateField(help_text='When the subscription started')),
                ('renewal_date', models.DateField(help_text='Next renewal date (auto-calculated)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is currently active')),
                ('category', models.CharField(blank=True, help_text='Category for grouping subscriptions', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['renewal_date'],
            },
        ),
    ]
