# Generated by Django 5.2.6 on 2025-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly subscription price (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly subscription price (optional)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Current billing frequency', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Current subscription cost (based on billing cycle)', max_digits=10),
        ),
    ]
